### ISSUE TITLE
gRPC error on channel open

### ISSUE THREAD

**Issue by artall64** [celer-network/Celer-Web-SDK#7]
![image](https://user-images.githubusercontent.com/2612218/52870066-3a583400-3104-11e9-96ba-aabdfcebfdc5.png)

This happened after commit:
https://github.com/celer-network/Celer-Web-SDK/commit/1e43834a843954b7d29727801e6b956751fce56e

**Comment by Dominator008** [comment]
This means the Celer client is unable to find your local state storage. Currently, the `StoreDir` field in `profile.json` is empty, and Celer client will put the local database in a temporary directory. I will change that and update the README.

For now, you can generate a new keystore and retry.

**Comment by Dominator008** [comment]
Default folder updated: https://github.com/celer-network/celer-client/commit/429cc3f256f1fa0382ebe8aa35e86454db92d5da#diff-b3680394fd052d9c99918f9b4d39f71eL9

**Comment by artall64** [comment]
Yes, it works. 
In case I launch several `celler_client` one machine, should I specify different `StoreDir` for them?

**Comment by Dominator008** [comment]
As long as the addresses in the `keystore` JSON are distinct, `celer_client` stores them separately under `StoreDir`.
